Passeio.web/Models/ErrorViewModel.cs
namespace Passeio.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Passeio.web/Models/ViewModels/DetalhesViewModel.cs
namespace Passeio.web.Models.ViewModels
{
    public class DetalhesViewModel
    {
        public Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Localizacao { get; set; }
        public string UsuarioCriador { get; set; }
        public string Imagem { get; set; }
    }
}

Passeio.web/Models/ViewModels/EditarViewModel.cs
namespace Passeio.web.Models.ViewModels
{
    public class EditarViewModel
    {
        public Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Localizacao { get; set; }
        public string Imagem { get; set; }
    }
}

Passeio.web/Models/ViewModels/LocalViewModel.cs
using Passeio.web.Enums;

namespace Passeio.web.Models.ViewModels
{
    public class LocalViewModel
    {
        public Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Localizacao { get; set; }
        public string UsuarioCriador { get; set; }
        public string Imagem { get; set; }
    }
}

Passeio.web/Controllers/LocalController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NToastNotify;
using Passeio.web.Dtos.Local;
using Passeio.web.Models.ViewModels;
using RestSharp;

namespace Passeio.web.Controllers
{
    public class LocalController : Controller
    {
        private readonly string passeioApi;
        private readonly IToastNotification _toastNotification;

        public LocalController(IToastNotification toastNotification)
        {
            passeioApi = "http://passeio.api:8080";
            _toastNotification = toastNotification;
        }
        public IActionResult Index()
        {
            var client = new RestClient(passeioApi);
            var rest = $"api/local/listar";
            var request = new RestRequest(rest, Method.Get);
            var response = client.Execute(request);
            if (response.IsSuccessful)
            {
                var localViewModel = JsonConvert.DeserializeObject<List<LocalViewModel>>(response.Content!);
                return View(localViewModel);
            }

            return View();
        }

        [HttpGet]
        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(LocalViewModel localViewModel)
        {
            var criarLocalDto = new CriarLocalDto
            {
                Titulo = localViewModel.Titulo,
                Descricao = localViewModel.Descricao,
                Localizacao = localViewModel.Localizacao,
                UsuarioCriador = localViewModel.UsuarioCriador,
                Imagem = localViewModel.Imagem
            };
            var client = new RestClient(passeioApi);
            var rest = $"api/local/criar";
            var request = new RestRequest(rest, Method.Post);
            request.AddBody(criarLocalDto);
            var response = client.Execute(request);
            if(response.IsSuccessful)
            {
                _toastNotification.AddSuccessToastMessage("Local cadastrado com sucesso!");
                return RedirectToAction(nameof(Index));
            }

            _toastNotification.AddErrorToastMessage(response.Content);
            return View(localViewModel);
        }

        public IActionResult Editar(Guid localId)
        {
            var client = new RestClient(passeioApi);
            var rest = $"api/local/buscarParaEdicao/{localId}";
            var request = new RestRequest(rest);
            var response = client.Execute(request);
            if(response.IsSuccessful)
            {
                var editarViewModel = JsonConvert.DeserializeObject<EditarViewModel>(response.Content!);
                return View(editarViewModel);
            }

            return View(nameof(Index));
        }


        [HttpPost]
        public IActionResult Editar(EditarViewModel editarViewModel)
        {
            var editarLocalDto = new EditarLocalDto
            {
                Id = editarViewModel.Id,
                Titulo = editarViewModel.Titulo,
                Descricao = editarViewModel.Descricao,
                Localizacao = editarViewModel.Localizacao,
                Imagem = editarViewModel.Imagem,
            };

            var client = new RestClient(passeioApi);
            var rest = $"api/local/editar";
            var request = new RestRequest(rest, Method.Put);
            request.AddBody(editarLocalDto);
            var response = client.Execute(request);
            if (response.IsSuccessful)
            {
                _toastNotification.AddSuccessToastMessage("Suas alterações foram salvas com sucesso!");
                return RedirectToAction(nameof(Index));
            }

            _toastNotification.AddErrorToastMessage(response.Content);
            return View(editarViewModel);
        }

        public IActionResult Deletar(Guid localId)
        {
            var client = new RestClient(passeioApi);
            var rest = $"api/local/deletar/{localId}";
            var request = new RestRequest(rest, Method.Patch);
            var response = client.Execute(request);
            if (response.IsSuccessful)
            {
                _toastNotification.AddSuccessToastMessage("Local excluído!");
                return RedirectToAction(nameof(Index));
            }

            _toastNotification.AddErrorToastMessage(response.Content);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(Guid localId)
        {
            var client = new RestClient(passeioApi);
            var rest = $"api/local/buscar/{localId}";
            var request = new RestRequest(rest);
            request.AddBody(localId);
            var response = client.Execute(request);
            if (response.IsSuccessful)
            {
                var detalhesViewModel = JsonConvert.DeserializeObject<DetalhesViewModel>(response.Content!);
                return View(detalhesViewModel);
            }
            _toastNotification.AddErrorToastMessage(response.Content);
            return RedirectToAction(nameof(Index));
        }
    }
}

Passeio.web/Views/Local/Criar.cshtml
@model Passeio.web.Models.ViewModels.LocalViewModel

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localizacao" class="control-label"></label>
                <input asp-for="Localizacao" class="form-control" />
                <span asp-validation-for="Localizacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioCriador" class="control-label"></label>
                <input asp-for="UsuarioCriador" class="form-control" />
                <span asp-validation-for="UsuarioCriador" class="text-danger"></span>
            </div>
            <!--Imagem-->
            <div class="form-group d-none">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Camera</div>
                <div class="panel-body">
                    <div id="mac_camera"></div>
                    <!-- botão para tirar foto -->
                    <button type="button" class="btn btn-secondary" disabled" value="Capturar Imagem" onClick="captura_imagem()"><i class="bi bi-camera"></i> Capturar</button>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Foto Capturada</div>
                <div class="panel-body">
                    <div id="resultado">Sua imagem capturada vai aparecer aqui.</div>
                </div>
                <br />
                <br />
            </div>
            <!--Termina Imagem-->

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista de locais</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/lib/webcamjs/webcam.min.js"></script>
    <script src="~/js/camera.js"></script>
}

Passeio.web/Views/Local/Detalhes.cshtml
@using Passeio.web.Models.ViewModels;
@model DetalhesViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<div class="card shadow-lg card-profile-top">
    <div class="row card-body justify-content-between">
        <h1 class="col-auto">@Model.Titulo</h1>
    </div>
</div>

@if (Model != null)
{
    <div class="card mt-3">
        <div class="row card-body">
            <div class="col-lg-2 col-md-3 col-sm-12">
                <h5 class="text-body">Imagem</h5>
                <img width="100" src="@Model.Imagem" />
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12">
                <h5 class="text-body">Título</h5>
                <p>@Model.Titulo</p>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12">
                <h5 class="text-body">Descrição</h5>
                <p>@Model.Descricao</p>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12">
                <h5 class="text-body">Localização</h5>
                <p>@Model.Localizacao</p>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12">
                <h5 class="text-body">Autor</h5>
                <p>@Model.UsuarioCriador</p>
            </div>
        </div>
    </div>

}
else
{
    <div class="card mt-3">
        <div class="card-body">
            <div class="alert alert-warning m-0 text-dark">
                Ainda não tem locais cadastrados.
            </div>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Voltar para lista de locais</a>
</div>

Passeio.web/Views/Local/Editar.cshtml
@model Passeio.web.Models.ViewModels.EditarViewModel

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" value="@Model.Id"/>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localizacao" class="control-label"></label>
                <input asp-for="Localizacao" class="form-control" />
                <span asp-validation-for="Localizacao" class="text-danger"></span>
            </div>
            <!--Imagem-->
            <div class="form-group d-none">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Camera</div>
                <div class="panel-body">
                    <div id="mac_camera"></div>
                    <!-- botão para tirar foto -->
                    <button type="button" class="btn btn-secondary" disabled" value="Capturar Imagem" onClick="captura_imagem()"><i class="bi bi-camera"></i> Capturar</button>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Foto Capturada</div>
                <div class="panel-body">
                    <div id="resultado">Sua imagem capturada vai aparecer aqui.</div>
                </div>
                <br />
                <br />
            </div>
            <!--Termina Imagem-->
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista de locais</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/lib/webcamjs/webcam.min.js"></script>
    <script src="~/js/camera.js"></script>
}

Passeio.web/Views/Local/Index.cshtml
@using Passeio.web.Enums;
@using Passeio.web.Models.ViewModels;
@model List<LocalViewModel>

@{
    ViewData["Title"] = "Lista";
}

<div class="jumbotron">
    <h1>.NET 💜 Azure</h1>
    <p class="lead">Example .NET app to Azure App Service.</p>
</div>

@if (Model != null && Model.Any())
{
    foreach (var local in Model)
    {
        <div class="card mt-3">
            <div class="row card-body">
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <h5 class="text-body">Imagem</h5>
                    <img width="100" src="@local.Imagem"/>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <h5 class="text-body">Título</h5>
                    <p>@local.Titulo</p>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <h5 class="text-body">Descrição</h5>
                    <p>@local.Descricao</p>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <h5 class="text-body">Localização</h5>
                    <p>@local.Localizacao</p>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <h5 class="text-body">Autor</h5>
                    <p>@local.UsuarioCriador</p>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-12">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownOpcoes" data-bs-toggle="dropdown" aria-expanded="false">
                            opções
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownOpcoes">
                            <li><a class="dropdown-item" asp-controller="Local" asp-action="Editar" asp-route-localId="@local.Id"><i class="bi bi-pen"></i>Editar</a></li>
                            <li><a class="dropdown-item" asp-controller="Local" asp-action="Detalhes" asp-route-localId="@local.Id"><i class="bi bi-card-text"></i>Detalhes</a></li>
                            <li><a class="dropdown-item text-danger" data-bs-toggle="modal" data-bs-target="#ExcluirModal" style="cursor: pointer;"><i class="bi bi-trash"></i>Excluir</a></li>
                        </ul>
                    </div>
                </div>
                <partial name="_ConfirmacaoDeExclusao" view-data='@new ViewDataDictionary(ViewData) { {"localId", local.Id }, {"tituloDoLugar", local.Titulo} }' />
            </div>
        </div>
    }
}
else
{
<div class="card mt-3">
    <div class="card-body">
        <div class="alert alert-warning m-0 text-dark">
            Ainda não tem locais cadastrados.
        </div>
    </div>
</div>
}

Passeio.web/Views/Local/_ConfirmacaoDeExclusao.cshtml
<!-- Modal -->
<div class="modal fade" id="ExcluirModal" tabindex="-1" role="dialog" aria-labelledby="ExcluirModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ExcluirModalLabel">Exclusão!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Tem certeza que deseja excluir o lugar @ViewData["tituloDoLugar"]? 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Voltar</button>
                <a type="button" class="btn btn-danger" asp-controller="Local" asp-action="Deletar" asp-route-localId="@ViewData["localId"]">Confirmar</a>
            </div>
        </div>
    </div>
</div>

Passeio.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Passeio.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Passeio.web.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Passeio.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Passeio.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>